umijs/umi-plugin-qiankun

README.md, examples/app1/.env, examples/app2/.env, src/slave/index.ts
热更新时webpack bootstrap会发ajax拉取hot-update[hash].json，此时需要配置子应用publicPath为绝对地址
=> demo:子应用支持hot-update

examples/app1/.umirc.js, examples/app2/.umirc.js
This PR was mearged,  https://github.com/umijs/umi-plugin-qiankun/pull/13
And now we can using dynamicImport.
=> demo: switch on dynamicImport

examples/master/app.js, package.json, src/master/runtimePlugin.ts
see https://github.com/umijs/umi/pull/3027
=> :bug: use mergeAsyncConfig api instead

src/master/index.ts
https://github.com/umijs/qiankun/issues/87
=> :bug: fix empty options in compile time

package.json, src/master/runtimePlugin.ts, src/types.ts
close https://github.com/umijs/qiankun/issues/88
https://github.com/umijs/qiankun/pull/89
=> :sparkles: get runtime LifeCycles config

examples/app1/app.js, examples/app2/app.js, examples/master/app.js, package.json, src/slave/index.ts
对于之前自己挂全局变量方式的应用来看，可能算是一个 breaking change (造成两次渲染)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi-plugin-qiankun/26)
=> :sparkles: 使用 qiankun 内置的 context variable 做运行时判断

README.md
=> :pencil: supplement runtime options

README.md, examples/app2/app.js, examples/master/mock/app.js, src/master/runtimePlugin.ts, src/types.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi-plugin-qiankun/28)
=> :sparkles: 允许主应用通过 props 传递数据导子应用

.eslintrc, .eslintrc.js, .gitignore, .prettierrc, .prettierrc.js, package.json, src/master/index.ts, src/master/runtimePlugin.ts, src/slave/index.ts, src/slave/lifecycles.ts, src/slave/runtimePlugin.ts, src/types.ts
=> :art: add linter and fix errors

.eslintrc.js, .prettierignore, .prettierrc.js, .travis.yml, package.json, src/master/index.ts, src/master/runtimePlugin.ts, src/slave/index.ts, src/slave/lifecycles.ts, src/types.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi-plugin-qiankun/31)
=> 🚨 supplement eslint rules and remove the error

.travis.yml, package.json, src/__tests__/common.test.ts, src/common.ts, src/master/runtimePlugin.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi-plugin-qiankun/36)
=> ✅ fix the path prefix match bug and add unit test

examples/app1/.umirc.js, examples/app2/.umirc.js, src/master/index.ts, src/slave/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi-plugin-qiankun/38)
=> :bug: 修复 slave 配置为空启动失败的问题

src/slave/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi-plugin-qiankun/39)
=> :bug: kill Multiple assets emit to the same filename warning

src/slave/index.ts
close https://github.com/umijs/umi/issues/3438
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi-plugin-qiankun/40)
=> :bug: 修复 sourcemap 冲突的问题

src/__tests__/common.test.ts, src/common.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi-plugin-qiankun/43)
=> :bug: 修复 pathPrefix 配置带斜杠时出现的路径匹配问题

README.md, src/slave/index.ts
see https://github.com/umijs/umi/issues/3438#issuecomment-552273446
使用 umi 新版本 api 支持 https://github.com/umijs/umi/pull/3653
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi-plugin-qiankun/42)
=> :bug: port 可能无法从 process 里获取到

package.json, src/slave/index.ts
ref 
https://github.com/umijs/qiankun/pull/147
umi 的这个特性发布后可以合并
https://github.com/umijs/umi/pull/3611
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi-plugin-qiankun/41)
=> :sparkles: 使用 qiankun 提供的 runtime publicPath

src/slave/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi-plugin-qiankun/44)
=> :sparkles: umi bundle script 自动添加 entry 标记

src/master/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi-plugin-qiankun/47)
=> :sparkles: 兼容遗留的配置了重名路由的场景

src/slave/index.ts
Close https://github.com/umijs/umi/issues/3822
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi-plugin-qiankun/48)
=> :sparkles: 子应用默认开启 runtimePublicPath

src/slave/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi-plugin-qiankun/52)
=> :bug: fix live public path bug while sub app open independent

src/slave/index.ts
ref https://github.com/umijs/umi/pull/3968
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi-plugin-qiankun/54)
=> :bug: modifyHTMLWithAST need to return cheerio

src/master/runtimePlugin.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi-plugin-qiankun/57)
=> :sparkles: 支持 base 为数组的场景，提供 getMatchedBase 方法供子应用获取当前匹配的 base

src/master/index.ts
resolve https://github.com/umijs/qiankun/issues/390
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi-plugin-qiankun/60)
=> :sparkles: 支持使用 rootExports.ts

src/common.ts, src/index.ts, src/master/index.ts, src/master/runtimePlugin.ts, src/slave/index.ts, src/types.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/umi-plugin-qiankun/61)
=> :sparkles: 新增 shoudNotModifyMountElementId 配置用于关闭对 mountElementId 的变更
